server:
  port: 8080
  servlet:
    session:
      timeout: 120m
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    threads:
      min-spare: 30
spring:
  datasource:
    hikari:
      platform: h2
      jdbc-url: jdbc:h2:tcp://localhost/~/kakaobank_test # jdbc:h2:mem:testdb #  -- In-memory 방식
      driver-class-name: org.h2.Driver
      username: SA
      password:
  #  expire:
#    products: 5000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql : true
  data:
    redis:
      host: localhost
      port: 6379
logging.level:
  org.hibernate.SQL: debug
api:
  kakao:
    blog:
      baseUri: http://localhost:8081
      reqUri: /search/blog
    authorization: KakaoAK 7905d8d8bf472226bd6f6c0900b0b4b5
  naver:
    blog:
      baseUri: http://localhost:8082
      reqUri: /search/blog
    clientId: A6Kk8FWlTT51IPPsutdZ
    clientSecret: U6ez5hu5fu
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 10
        errorThresholdPercentage: 70
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

